export enum LeadStatus {
  PROSPECT = 'PROSPECT',
  QUOTED = 'QUOTED',
  CALL_BACK_LATER = 'CALL_BACK_LATER',
  SHOPPING_AROUND = 'SHOPPING_AROUND',
  NOT_INTERESTED = 'NOT_INTERESTED',
  NEEDS_LOCALLY = 'NEEDS_LOCALLY',
  WE_DONT_SALE = 'WE_DONT_SALE',
}
