export enum ReplacementStatus {
  REQUESTED = 'REQUESTED',
  YARD_CONTACTED = 'YARD_CONTACTED',
  WAITING_YARD_RESPONSE = 'WAITING_YARD_RESPONSE',
  APPROVED = 'APPROVED',
  REPLACEMENT_ORDERED = 'REPLACEMENT_ORDERED',
  REPLACEMENT_SHIPPED = 'REPLACEMENT_SHIPPED',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
}
