export enum ReplacementStatus {
  WAITING_YARD_RESPONSE = 'WAITING_YARD_RESPONSE',
  YARD_CONTACTED = 'YARD_CONTACTED',
  AGREED = 'AGREED',
  DISAGREED = 'DISAGREED',
  YARD_REFUNDING = 'YARD_REFUNDING',
  YARD_DOESNT_HAVE_REPLACEMENT = 'YARD_DOESNT_HAVE_REPLACEMENT',
  SHIPPED = 'SHIPPED',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED = 'DELIVERED',
}
