export enum ReplacementStatus {
  YARD_CONTACTED = 'YARD_CONTACTED',
  WAITING_YARD_RESPONSE = 'WAITING_YARD_RESPONSE',
  APPROVED = 'APPROVED',
  SHIPPED = 'SHIPPED',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED = 'DELIVERED',
}
