export enum ShipmentStatus {
  PENDING = 'PENDING',
  LOCATING = 'LOCATING',
  PRE_PROCESSING = 'PRE_PROCESSING',
  PURCHASE = 'PURCHASE',
  SHIPPED = 'SHIPPED',
  IN_TRANSIT = 'IN_TRANSIT',
  DISPUTED = 'DISPUTED',
  DELIVERED = 'DELIVERED',
  DELAYED = 'DELAYED',
  CANCELLED = 'CANCELLED',
}
