ALTER TYPE "ShipmentStatus" ADD VALUE IF NOT EXISTS 'LOCATING';
ALTER TYPE "ShipmentStatus" ADD VALUE IF NOT EXISTS 'PRE_PROCESSING';
ALTER TYPE "ShipmentStatus" ADD VALUE IF NOT EXISTS 'PURCHASE';
ALTER TYPE "ShipmentStatus" ADD VALUE IF NOT EXISTS 'SHIPPED';

ALTER TABLE "Shipment"
ALTER COLUMN "bolNumber" DROP NOT NULL;
