export const NOTIFICATION_TYPES = {
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_UPDATED: 'ORDER_UPDATED',
  ORDER_NOTE_CREATED: 'ORDER_NOTE_CREATED',
  SHIPMENT_CREATED: 'SHIPMENT_CREATED',
  SHIPMENT_STATUS_UPDATED: 'SHIPMENT_STATUS_UPDATED',
  SHIPMENT_NOTE_CREATED: 'SHIPMENT_NOTE_CREATED',
  SHIPMENT_ACTIVITY: 'SHIPMENT_ACTIVITY',
} as const;

export const NOTIFICATION_ENTITY_TYPES = {
  ORDER: 'ORDER',
  SHIPMENT: 'SHIPMENT',
} as const;

