// Generated from provided CRM source documents. Do not edit manually.
export const DOCUMENT_VEHICLE_MAKES = [
  "Acura",
  "Alfa",
  "AMC",
  "Aston",
  "Asuna",
  "Audi",
  "Austin",
  "Autocar",
  "Avanti",
  "Bentley",
  "BMW",
  "Bricklin",
  "Brockway",
  "Buick",
  "Cadillac",
  "Checker",
  "Chevy",
  "Chrysler",
  "Citroen",
  "Cushman",
  "Daewoo",
  "Daihatsu",
  "Delorean",
  "Desoto",
  "Diamond",
  "Dodge",
  "Eagle",
  "Edsel",
  "Ferrari",
  "Fiat",
  "Fisker",
  "Ford",
  "Freightliner",
  "Freuhauf",
  "FWD",
  "Genesis",
  "Geo",
  "GMC",
  "Grenadier",
  "Hino",
  "Honda",
  "Hudson",
  "Hummer",
  "Hyundai",
  "IH",
  "Infiniti",
  "Isuzu",
  "Jaguar",
  "Jeep",
  "Kaiser",
  "Kenworth",
  "Kia",
  "Lada",
  "Lamborghini",
  "Lancia",
  "LandRover",
  "Lexus",
  "Lincoln",
  "Lotus",
  "Lucid",
  "Mac",
  "Marmon",
  "Maserati",
  "Maybach",
  "Mazda",
  "McLaren",
  "Mercedes",
  "Mercury",
  "MG",
  "Mini",
  "Mitsubishi",
  "Morris",
  "Nash",
  "Nissan",
  "Oldsmobile",
  "Opel",
  "Oshkosh",
  "Pace",
  "Packard",
  "Pantera",
  "Peterbilt",
  "Peugeot",
  "Plymouth",
  "Polestar",
  "Pontiac",
  "Porsche",
  "Ram",
  "Renault",
  "REO",
  "Rivian",
  "RollsRoyce",
  "Rover",
  "Saab",
  "Saturn",
  "Scion",
  "Seat",
  "Simca",
  "Smart",
  "SterlingRover",
  "Studebaker",
  "Subaru",
  "Sunbeam",
  "Suzuki",
  "Tesla",
  "Thomas",
  "Toyota",
  "Triumph",
  "Utilimaster",
  "VinFast",
  "Volkswagen",
  "Volvo",
  "VPG",
  "Western",
  "White",
  "Willys",
  "Winnebago",
  "Yugo"
] as const;

export const DOCUMENT_MODELS_BY_MAKE = {
  "Acura": [
    "ADX",
    "CL",
    "CSX",
    "EL",
    "ILX",
    "Integra",
    "Legend",
    "MDX",
    "NSX",
    "RDX",
    "RL",
    "RLX",
    "RSX",
    "SLX",
    "TL",
    "TLX",
    "TSX",
    "Vigor",
    "ZDX"
  ],
  "Alfa": [
    "147",
    "164 Sedan",
    "1750",
    "4C",
    "Alfetta",
    "Giulia",
    "Giulia 1600",
    "Giulietta",
    "GTV6",
    "Milano",
    "Mito",
    "Spider-1600",
    "Spider-1600 Duetto",
    "Spider-2000",
    "Stelvio",
    "Tonale"
  ],
  "AMC": [
    "Ambassador",
    "American",
    "AMX",
    "Classic",
    "Concord",
    "Eagle",
    "Gremlin",
    "Hornet",
    "Javelin",
    "Marlin",
    "Matador",
    "Other",
    "Pacer",
    "Rambler",
    "Rebel",
    "Spirit"
  ],
  "Aston": [
    "Martin"
  ],
  "Asuna": [
    "Other"
  ],
  "Audi": [
    "100",
    "200",
    "4000 2 & 4 Door Sedan",
    "4000 Quattro",
    "5000 & 5000 Quattro",
    "80 Series",
    "90 Series",
    "A3",
    "A4",
    "A5",
    "A6",
    "A6 e-tron",
    "A7",
    "A8",
    "AllRoad",
    "AllRoad A4",
    "AllRoad A6",
    "Cabriolet",
    "Coupe GT",
    "Coupe Quattro",
    "e-tron",
    "e-tron GT",
    "e-tron S",
    "Fox",
    "Q3",
    "Q4 e-tron",
    "Q5",
    "Q6 e-tron",
    "Q7",
    "Q8",
    "Q8 e-tron",
    "R8",
    "RS e-tron GT",
    "RS Q8",
    "RS3",
    "RS4",
    "RS5",
    "RS6",
    "RS7",
    "S e-tron GT",
    "S3",
    "S4",
    "S5",
    "S6",
    "S6 e-tron",
    "S7",
    "S8",
    "Sport Coupe",
    "SQ5",
    "SQ6 e-tron",
    "SQ7",
    "SQ8",
    "SQ8 e-tron",
    "Super 90",
    "TT",
    "V8 Quattro"
  ],
  "Austin": [
    "Mini",
    "Other"
  ],
  "Autocar": [
    "Other"
  ],
  "Avanti": [
    "Other"
  ],
  "Bentley": [
    "Arnage",
    "Azure",
    "Bentayga",
    "Brooklands",
    "Continental",
    "Corniche",
    "Eight",
    "Flying Spur",
    "Mulsanne",
    "Other",
    "Turbo R"
  ],
  "BMW": [
    "128i",
    "135i",
    "1602",
    "1800",
    "1M",
    "2002",
    "228i",
    "230i",
    "2500",
    "2800",
    "3.0",
    "318i",
    "320i",
    "323i",
    "325e",
    "325i",
    "328",
    "328i GT",
    "330e",
    "330i",
    "330i GT",
    "335i",
    "335i GT",
    "340i",
    "340i GT",
    "428i",
    "430i",
    "435i",
    "440i",
    "524TD",
    "525i",
    "528e",
    "528i",
    "530e",
    "530i",
    "533i",
    "535i",
    "535i GT",
    "540i",
    "545i",
    "550e",
    "550i",
    "550i GT",
    "630CSi",
    "633CSi",
    "635CSi",
    "640i",
    "640i GT",
    "645Ci",
    "650i",
    "728",
    "732",
    "733i",
    "735i",
    "740e",
    "740i",
    "745e",
    "745i",
    "750e",
    "750i",
    "760i",
    "840ci",
    "840i",
    "850i",
    "ActiveE",
    "ActiveHybrid 3",
    "ActiveHybrid 5",
    "ActiveHybrid 7",
    "Alpina B6",
    "Alpina B7",
    "Alpina B8",
    "Alpina XB7",
    "I3",
    "I4",
    "I5",
    "I7",
    "I8",
    "IX",
    "L6",
    "M1",
    "M2",
    "M235i",
    "M240i",
    "M3",
    "M340i",
    "M4",
    "M440i",
    "M5",
    "M550i",
    "M6",
    "M760i",
    "M8",
    "M850i",
    "Mini Cooper",
    "Mini Cooper Clubman",
    "Mini Cooper Countryman",
    "Mini Cooper Paceman",
    "Other",
    "X1",
    "X2",
    "X3",
    "X3M",
    "X4",
    "X4M",
    "X5",
    "X5M",
    "X6",
    "X6M",
    "X7",
    "XM",
    "Z3",
    "Z4",
    "Z8"
  ],
  "Bricklin": [
    "Other"
  ],
  "Brockway": [
    "Other"
  ],
  "Buick": [
    "Allure",
    "Apollo",
    "Cascada",
    "Century",
    "Electra (1979 Down)",
    "Electra (1980 Up)",
    "Enclave",
    "Encore",
    "Encore GX",
    "Envision",
    "Envista",
    "Lacrosse",
    "LeSabre (1979 Down)",
    "LeSabre (1980 Up)",
    "Limited",
    "Lucerne",
    "Other",
    "Park Ave (1979 Down)",
    "Park Ave (1980 Up)",
    "Rainier",
    "Reatta",
    "Regal",
    "Regal Somerset (1984 Down)",
    "Rendezvous",
    "Riviera",
    "Roadmaster (1979 Down)",
    "Roadmaster (1980 Up)",
    "Skyhawk",
    "Skylark",
    "Somerset (1985 Up)",
    "Special",
    "Terraza",
    "Verano"
  ],
  "Cadillac": [
    "Allante",
    "ATS",
    "Brougham",
    "Catera",
    "Cimarron",
    "Concours",
    "CT4",
    "CT5",
    "CT6",
    "CTS",
    "DeVille (1979 Down)",
    "DeVille (1980 Up)",
    "DHS",
    "DTS (2005 Down)",
    "DTS (2006 Up)",
    "Eldorado (1966 Down)",
    "Eldorado (1967 Up)",
    "ELR",
    "Escalade",
    "Escalade IQ",
    "Escalade-ESV",
    "Escalade-EXT",
    "Fleetwood (1979 Down)",
    "Fleetwood (1980 Up)",
    "LYRIQ",
    "OPTIQ",
    "Other",
    "Seville (incl STS)",
    "SRX",
    "STS",
    "XLR",
    "XT4",
    "XT5",
    "XT6",
    "XTS"
  ],
  "Checker": [
    "Cab",
    "Other"
  ],
  "Chevy": [
    "Astra",
    "Astro",
    "Aveo",
    "Beretta",
    "Blazer (2019 Up)",
    "Blazer EV",
    "Blazer, Full Size (1994 Down)",
    "Blazer, S10/S15",
    "Bolt",
    "Bolt EUV",
    "BrightDrop 400",
    "BrightDrop 600",
    "C2",
    "Camaro",
    "Caprice (1979 Down)",
    "Caprice (1980 Up)",
    "Captiva Sport",
    "Cavalier",
    "Celebrity",
    "Chevelle",
    "Chevette",
    "Chevy Pickup FWD (Non US Mkt)",
    "Chevy Small Car (Non US Mkt)",
    "Citation",
    "City Express",
    "Cobalt",
    "Corsa",
    "Corsica",
    "Corvair",
    "Corvette",
    "Cruze",
    "El Camino (1963 Down)",
    "El Camino (1964-1977)",
    "El Camino (1978 Up)",
    "Epica",
    "Equinox",
    "Equinox EV",
    "HHR",
    "Impala (1979 Down)",
    "Impala (1980 Up)",
    "Lumina Car",
    "Lumina Van",
    "Luv (See Also Isuzu Mini P-Up)",
    "Malibu",
    "Meriva",
    "Metro",
    "Monte Carlo",
    "Monza",
    "Nova (1968 Up)",
    "Nova & Chevy II (1967 Down)",
    "Optra",
    "Orlando",
    "Other",
    "Prizm",
    "S10/S15/Sonoma",
    "Silverado EV",
    "Sonic",
    "Spark",
    "Spectrum",
    "Sprint",
    "SS",
    "SSR",
    "Suburban-10 (1988 Down)",
    "Suburban-1000 (1963-1966)",
    "Suburban-1500",
    "Suburban-20 (1988 Down)",
    "Suburban-2500 (1967 Up)",
    "Suburban-30 (1966 Down)",
    "Suburban-3500",
    "Tahoe",
    "Tigra",
    "Tornado",
    "Tracker",
    "TrailBlazer",
    "TrailBlazer-EXT",
    "Traverse",
    "Trax",
    "Truck-10 Series (1987 Down)",
    "Truck-1500 Series (1988-1999)",
    "Truck-20 Series (1988 Down)",
    "Truck-2500 Series (1988-2000)",
    "Truck-30 Series (1988 Down)",
    "Truck-3500 Series (1988-2001)",
    "Truck-Avalanche 1500",
    "Truck-Avalanche 2500",
    "Truck-C3100",
    "Truck-C3600",
    "Truck-C3800",
    "Truck-Colorado",
    "Truck-Forward Control",
    "Truck-Kodiak",
    "Truck-Luv Mini Pup",
    "Truck-S10/S15/Sonoma",
    "Truck-Silverado 1500 (1999 Up)",
    "Truck-Silverado 2500 (1999 Up)",
    "Truck-Silverado 3500 (2001 Up)",
    "Truck-Tilt Cab",
    "Uplander",
    "Van 10",
    "Van 20",
    "Van 30",
    "Van Express 1500",
    "Van Express 2500",
    "Van Express 3500",
    "Vectra",
    "Vega",
    "Venture",
    "Volt",
    "Zafira"
  ],
  "Chrysler": [
    "200",
    "300",
    "300M",
    "Aspen",
    "Atos",
    "Attitude",
    "Cirrus",
    "Concorde",
    "Conquest",
    "Cordoba",
    "Crossfire",
    "E Class",
    "Fifth Avenue - FWD",
    "Fifth Avenue - RWD (1979 Up)",
    "Imperial",
    "Laser",
    "Lebaron",
    "LHS",
    "New Yorker - FWD",
    "New Yorker - RWD",
    "Newport",
    "Other",
    "Pacifica",
    "Prowler",
    "PT Cruiser",
    "Sebring",
    "TC",
    "Town and Country",
    "Voyager"
  ],
  "Citroen": [
    "Other"
  ],
  "Cushman": [
    "Cushman"
  ],
  "Daewoo": [
    "Lanos",
    "Leganza",
    "Nubira"
  ],
  "Daihatsu": [
    "Charade",
    "Hijet",
    "Rocky"
  ],
  "Delorean": [
    "Other"
  ],
  "Desoto": [
    "Other"
  ],
  "Diamond": [
    "Reo"
  ],
  "Dodge": [
    "400",
    "600",
    "Aries",
    "Aspen",
    "Avenger",
    "Caliber",
    "Caravan",
    "Challenger (Chrysler)",
    "Challenger (Mitsubishi)",
    "Charger",
    "Colt (not Vista)",
    "Colt Vista",
    "Cricket",
    "D50/Ram 50 (See also Plymouth Arrow Truck)",
    "Dakota",
    "Dart",
    "Daytona",
    "Diplomat",
    "Durango",
    "Dynasty",
    "Hornet",
    "Intrepid",
    "Journey",
    "Lancer",
    "Magnum",
    "Mirada",
    "Monaco (1978 Down)",
    "Monaco (1990 Up)",
    "Neon",
    "Nitro",
    "Omni",
    "Other",
    "Raider",
    "Ramcharger",
    "Rampage",
    "Shadow",
    "Spirit",
    "St Regis",
    "Stealth",
    "Stratus",
    "Truck-100 Series (1989 Down)",
    "Truck-150 (1978-1993)",
    "Truck-1500 (1994 Up)",
    "Truck-200 Series (1980 Down)",
    "Truck-250 Series (1981-1993)",
    "Truck-2500 Series (1994 Up)",
    "Truck-300 Series (1980 Down)",
    "Truck-350 Series (1981-1993)",
    "Truck-3500 (1994 Up)",
    "Truck-400 Series",
    "Truck-450 Series",
    "Truck-4500 Series",
    "Truck-5500 Series",
    "Truck-D50/Ram 50",
    "Truck-Dakota",
    "Truck-Forward Control",
    "Truck-Rampage",
    "Van (Sprinter 2500)",
    "Van (Sprinter 3500)",
    "Van 100",
    "Van 150",
    "Van 1500",
    "Van 200",
    "Van 250",
    "Van 2500",
    "Van 300",
    "Van 350",
    "Van 3500",
    "Verna",
    "Viper"
  ],
  "Eagle": [
    "2000 GTX",
    "Premier",
    "Summit",
    "Talon",
    "Vision"
  ],
  "Edsel": [
    "Other"
  ],
  "Ferrari": [
    "Other"
  ],
  "Fiat": [
    "1100R",
    "124 (1983 Down, includes Spider)",
    "124 Spider (2016 Up)",
    "128",
    "131/Brava",
    "500",
    "600",
    "850",
    "Other",
    "Spider (includes 2000)",
    "Strada",
    "X 1/9"
  ],
  "Fisker": [
    "Karma",
    "Ocean"
  ],
  "Ford": [
    "500",
    "Aerostar",
    "Aspire",
    "Bronco (Full Size)",
    "Bronco II",
    "Bronco Raptor",
    "Bronco Sport",
    "C-Max",
    "Contour",
    "Cortina",
    "Courier",
    "Crown Vic (1982 Down)",
    "Crown Vic (1983 Up)",
    "E Transit",
    "Ecosport",
    "Edge",
    "Escape",
    "Escort",
    "Excursion",
    "EXP",
    "Expedition",
    "Explorer",
    "Fairlane",
    "Fairmont",
    "Falcon",
    "Festiva",
    "Fiesta",
    "Five Hundred",
    "Flex",
    "Focus",
    "Focus RS",
    "Freestar",
    "Freestyle",
    "Fusion",
    "Galaxie",
    "Granada",
    "GT",
    "Ikon",
    "KA",
    "LTD (1978 Down)",
    "LTD (1979 Up)",
    "LTD II",
    "Maverick",
    "Maverick Pickup",
    "Mondeo",
    "Mustang",
    "Mustang Mach E",
    "Other",
    "Pinto",
    "Probe",
    "Ranchero (1957-1959)",
    "Ranchero (1960-1966)",
    "Ranchero (1967-1970)",
    "Ranchero (1971-1976)",
    "Ranchero (1977 up)",
    "Ranger",
    "Ranger Raptor",
    "Taurus",
    "Taurus X",
    "Tempo",
    "ThinkCity-Electric",
    "Thunderbird",
    "Torino",
    "Transit 150",
    "Transit 250",
    "Transit 350",
    "Transit Connect",
    "Truck F150 Lightning (Electric)",
    "Truck-Courier",
    "Truck-F100",
    "Truck-F150",
    "Truck-F150 Lightning (SVT Gas)",
    "Truck-F150 Raptor",
    "Truck-F250 not Super Duty (1999 Down)",
    "Truck-F250 Super Duty (1999 Up)",
    "Truck-F350 not Super Duty (1997 Down)",
    "Truck-F350 Super Duty (1999 Up)",
    "Truck-F450 not Super Duty (1997 Down)",
    "Truck-F450 Super Duty (1999 Up)",
    "Truck-F550 Super Duty (1999 Up)",
    "Truck-F600 not Super Duty (1994 Down)",
    "Truck-F600 Super Duty (2020 Up)",
    "Truck-Forward Control",
    "Truck-Ranger",
    "Van E100",
    "Van E150",
    "Van E200",
    "Van E250",
    "Van E300",
    "Van E350",
    "Van E450 Super Duty",
    "Van E550 Super Duty",
    "Windstar"
  ],
  "Freightliner": [
    "Other"
  ],
  "Freuhauf": [
    "Other"
  ],
  "FWD": [
    "Trucks"
  ],
  "Genesis": [
    "G70",
    "G80",
    "G90",
    "GV60",
    "GV70",
    "GV80"
  ],
  "Geo": [
    "Metro",
    "Prizm",
    "Spectrum",
    "Storm",
    "Tracker"
  ],
  "GMC": [
    "Acadia",
    "Hummer EV",
    "Jimmy, Full Size",
    "Jimmy, S10/S15",
    "Safari Van",
    "Sierra Denali EV",
    "Sprint",
    "Suburban-10 (1988 Down)",
    "Suburban-1000 (1965-1966)",
    "Suburban-1500 (2001 Down)",
    "Suburban-20 (1988 Down)",
    "Suburban-2500 (1967 Up)",
    "Suburban-30 (1965-1966)",
    "Syclone",
    "Terrain",
    "Truck-1000 Series (1966 Down)",
    "Truck-1500 Series (1999 Down)",
    "Truck-2500 Series (2000 Down)",
    "Truck-3500 Series (2001 Down)",
    "Truck-Canyon",
    "Truck-Envoy",
    "Truck-Envoy XL",
    "Truck-Envoy XUV",
    "Truck-Forward Control",
    "Truck-S10/S15/Sonoma",
    "Truck-Sierra 1500 (1999 Up)",
    "Truck-Sierra 2500 (1999 Up)",
    "Truck-Sierra 3500 (2001 Up)",
    "Truck-Sierra Denali",
    "Truck-Sierra Denali 1500 (2011 Up)",
    "Truck-Sierra Denali 2500 (2011 Up)",
    "Truck-Sierra Denali 3500 (2011 Up)",
    "Truck-Topkick",
    "Truck-Yukon (except XL)",
    "Truck-Yukon XL1500",
    "Truck-Yukon XL2500",
    "Typhoon",
    "Van 1000",
    "Van 1500",
    "Van 2500",
    "Van 3500",
    "Van Savana 1500",
    "Van Savana 2500",
    "Van Savana 3500"
  ],
  "Grenadier": [
    "1924",
    "Detour",
    "Grenadier Base",
    "Quartermaster",
    "Station Wagon"
  ],
  "Hino": [
    "Truck"
  ],
  "Honda": [
    "600",
    "Accord",
    "Acty",
    "Civic",
    "Clarity",
    "Clarity Electric",
    "Clarity Fuel Cell",
    "Crosstour",
    "CRV",
    "CRV e:FCEV",
    "CRX",
    "CRZ",
    "DelSol",
    "Element",
    "FCX",
    "Fit",
    "HRV",
    "Insight",
    "Odyssey",
    "Passport",
    "Pilot",
    "Prelude",
    "Prologue",
    "Ridgeline",
    "S2000"
  ],
  "Hudson": [
    "Other"
  ],
  "Hummer": [
    "H1",
    "H2",
    "H3",
    "Other"
  ],
  "Hyundai": [
    "Accent",
    "Azera",
    "Elantra",
    "Entourage",
    "Equus",
    "Excel",
    "Genesis",
    "Ioniq",
    "Ioniq 5",
    "Ioniq 6",
    "Kona",
    "Kona Electric",
    "Nexo",
    "Palisade",
    "Pony",
    "Santa Cruz",
    "Santa Fe",
    "Scoupe",
    "Sonata",
    "Stellar",
    "Tiburon",
    "Tucson",
    "Veloster",
    "Venue",
    "Veracruz",
    "XG Series"
  ],
  "IH": [
    "(Pickup & Travelall)",
    "Scout & Scout II",
    "Truck (Big)"
  ],
  "Infiniti": [
    "EX35",
    "EX37",
    "FX",
    "G20",
    "G25",
    "G35",
    "G37",
    "I30",
    "I35",
    "J30",
    "JX35",
    "M30",
    "M35",
    "M37",
    "M45",
    "M56",
    "Q40",
    "Q45",
    "Q50",
    "Q60",
    "Q70",
    "QX30",
    "QX4",
    "QX50",
    "QX55",
    "QX56",
    "QX60",
    "QX70",
    "QX80"
  ],
  "Isuzu": [
    "Amigo",
    "Ascender",
    "Axiom",
    "Gemini",
    "IMark",
    "Impulse",
    "Oasis",
    "Optima",
    "Reach",
    "Rodeo",
    "Stylus",
    "Trooper/Trooper II",
    "Truck (Big)",
    "Truck-(Mini Pickup)",
    "Truck-(Mini Pickup) Hombre",
    "Truck-i280 (Pickup)",
    "Truck-i290 (Pickup)",
    "Truck-i350 (Pickup)",
    "Truck-i370 (Pickup)",
    "Vehicross"
  ],
  "Jaguar": [
    "120",
    "140",
    "150",
    "E Pace",
    "F Pace",
    "F Type",
    "I Pace",
    "Mark 10",
    "S Type",
    "Sedan",
    "Vanden Plas (1997 Down)",
    "Vanden Plas (1998 to 2007)",
    "Vanden Plas (2008 Up)",
    "X Type",
    "XE",
    "XF",
    "XF Sportbrake",
    "XJ Series (2008 Up)",
    "XJ12",
    "XJ6",
    "XJ8 (2007 Down)",
    "XJ8 (2008 Up)",
    "XJR (1993)",
    "XJR (1995 to 1997)",
    "XJR (1998 to 2007)",
    "XJR (2008 Up)",
    "XJS",
    "XK Series (2007 Up)",
    "XK8",
    "XKE",
    "XKR (2006 Down)",
    "XKR (2007 Up)"
  ],
  "Jeep": [
    "Cherokee (except Grand Cherokee)",
    "CJSeries",
    "Comanche",
    "Commander",
    "Compass",
    "DJ Series",
    "FC Series",
    "Gladiator",
    "Grand Cherokee",
    "Grand Wagoneer",
    "J-Series",
    "Jeepster",
    "Liberty",
    "Patriot",
    "Renegade",
    "Station Wagon",
    "Truck",
    "Wagoneer (except Grand Wagoneer)",
    "Wrangler"
  ],
  "Kaiser": [
    "Other"
  ],
  "Kenworth": [
    "Other"
  ],
  "Kia": [
    "Amanti",
    "Besta",
    "Borrego",
    "Cadenza",
    "Carnival",
    "EV6",
    "EV9",
    "Forte",
    "K4",
    "K5",
    "K900",
    "Magentis",
    "Niro",
    "Niro EV",
    "Optima",
    "Rio",
    "Rondo",
    "Sedona",
    "Seltos",
    "Sephia",
    "Sorento",
    "Soul",
    "Spectra",
    "Sportage",
    "Stinger",
    "Telluride"
  ],
  "Lada": [
    "Other"
  ],
  "Lamborghini": [
    "Other"
  ],
  "Lancia": [
    "Other"
  ],
  "LandRover": [
    "Defender (1997 Down)",
    "Defender (2020 Up)",
    "Discovery (2004 Down)",
    "Discovery (2017 Up)",
    "Discovery Sport",
    "Freelander",
    "LR2",
    "LR3",
    "LR4",
    "Other",
    "Range Rover",
    "Range Rover Evoque",
    "Range Rover Sport",
    "Range Rover Velar"
  ],
  "Lexus": [
    "CT 200H",
    "ES250",
    "ES300",
    "ES300H",
    "ES330",
    "ES350",
    "GS F",
    "GS200t",
    "GS300",
    "GS350",
    "GS400",
    "GS430",
    "GS450h",
    "GS460",
    "GX460",
    "GX470",
    "GX550",
    "HS250H",
    "IS F",
    "IS200t",
    "IS250",
    "IS300",
    "IS350",
    "IS500",
    "LC500",
    "LC500h",
    "LFA",
    "LS400",
    "LS430",
    "LS460",
    "LS500",
    "LS500h",
    "LS600HL",
    "LX450",
    "LX470",
    "LX570",
    "LX600",
    "LX700h",
    "NX200t",
    "NX250",
    "NX300",
    "NX300h",
    "NX350",
    "NX350H",
    "NX450h+",
    "RC 200t",
    "RC 300",
    "RC 350",
    "RC F",
    "RX300",
    "RX330",
    "RX350",
    "RX350h",
    "RX350L",
    "RX400h",
    "RX450 Hybrid",
    "RX450 Hybrid L",
    "RX500h",
    "RZ300e",
    "RZ450e",
    "SC (excl 430)",
    "SC430",
    "TX350",
    "TX500h",
    "TX550h",
    "UX 200",
    "UX 250h",
    "UX 300h"
  ],
  "Lincoln": [
    "Aviator",
    "Blackwood",
    "Continental",
    "Corsair",
    "LS",
    "Mark LT",
    "Mark Series",
    "MKC",
    "MKS",
    "MKT",
    "MKX",
    "MKZ",
    "Nautilus",
    "Navigator",
    "Other (includes Town Car)",
    "Versailles",
    "Zephyr"
  ],
  "Lotus": [
    "Other"
  ],
  "Lucid": [
    "Air",
    "Gravity"
  ],
  "Mac": [
    "Other"
  ],
  "Marmon": [
    "Truck"
  ],
  "Maserati": [
    "BiTurbo",
    "Ghibli",
    "GranTurismo",
    "Grecale",
    "Grecale GT",
    "Levante",
    "Other",
    "Quattroporte"
  ],
  "Maybach": [
    "Other"
  ],
  "Mazda": [
    "1200",
    "1800",
    "2",
    "3",
    "323",
    "5",
    "6",
    "626",
    "808",
    "929",
    "Cosmo",
    "CX3",
    "CX30",
    "CX5",
    "CX50",
    "CX7",
    "CX70",
    "CX9",
    "CX90",
    "GLC",
    "Miata MX5",
    "Millenia",
    "MPV Van",
    "MX3",
    "MX30",
    "MX6",
    "Navajo",
    "Pickup-B1600",
    "Pickup-B1800",
    "Pickup-B2000",
    "Pickup-B2200",
    "Pickup-B2300",
    "Pickup-B2500",
    "Pickup-B2600",
    "Pickup-B3000",
    "Pickup-B4000",
    "Pickup-Rotary",
    "Protege",
    "RX2",
    "RX3",
    "RX4",
    "RX7",
    "RX8",
    "Tribute"
  ],
  "McLaren": [
    "540C",
    "570GT",
    "570S",
    "600LT",
    "620R",
    "650S",
    "675LT",
    "720S",
    "750S",
    "765LT",
    "Artura",
    "Elva",
    "GT",
    "GTS",
    "MP4 12C",
    "P1",
    "Senna",
    "Speedtail"
  ],
  "Mercedes": [
    "170",
    "190",
    "200",
    "218",
    "219",
    "220",
    "230-4 Cyl",
    "230-6 Cyl",
    "240D",
    "250",
    "260E",
    "280",
    "300D (includes CD/D/SD/TD)",
    "300E",
    "300SL",
    "320",
    "350",
    "380",
    "400",
    "420",
    "450",
    "500",
    "560",
    "600",
    "A Class",
    "AMG GT",
    "B Class",
    "C Class",
    "CL Class",
    "CLA Class",
    "CLE Class",
    "CLK",
    "CLS",
    "E Class",
    "EQB Class",
    "EQE Class",
    "EQE Class SUV",
    "EQS Class",
    "EQS Class SUV",
    "eSprinter 2500",
    "G Class",
    "GL Class",
    "GLA Class",
    "GLB Class",
    "GLC Class",
    "GLE Class",
    "GLK Class",
    "GLS Class",
    "Metris",
    "ML Series",
    "R Class",
    "S Class",
    "SL Class",
    "SLC Class",
    "SLK",
    "SLR",
    "SLS",
    "Sprinter 1500",
    "Sprinter 2500",
    "Sprinter 3500",
    "Sprinter 4500",
    "Truck"
  ],
  "Mercury": [
    "Bobcat",
    "Capri",
    "Comet",
    "Cougar",
    "Grand Marquis (1979 Down)",
    "Grand Marquis (1980 Up)",
    "LN7",
    "Lynx (except LN7)",
    "Marauder",
    "Mariner",
    "Marquis (not Grand)",
    "Merkur (includes XR4TI and Scorpio)",
    "Milan",
    "Monarch",
    "Montego",
    "Monterey",
    "Mountaineer",
    "Mystique",
    "Other",
    "Sable",
    "Topaz",
    "Tracer",
    "Villager",
    "Zephyr"
  ],
  "MG": [
    "MGB",
    "Midget",
    "Other"
  ],
  "Mini": [
    "(Austin)",
    "Cooper",
    "Cooper Clubman",
    "Cooper Countryman",
    "Cooper Paceman"
  ],
  "Mitsubishi": [
    "3000",
    "Cordia",
    "Diamante",
    "Eclipse",
    "Eclipse Cross",
    "Endeavor",
    "Expo",
    "Fuso",
    "Galant",
    "i MiEV",
    "Lancer",
    "Minicab",
    "Mirage",
    "Montero",
    "Montero-Sport",
    "Outlander",
    "Outlander Sport",
    "Pickup (See also Dodge D50)",
    "Precis",
    "Raider",
    "RVR",
    "Sigma",
    "Space Wagon",
    "Starion",
    "Tredia",
    "Van"
  ],
  "Morris": [
    "Other"
  ],
  "Nash": [
    "Other"
  ],
  "Nissan": [
    "1200",
    "1600",
    "200SX",
    "210",
    "240SX",
    "240Z",
    "260Z",
    "280Z",
    "280ZX",
    "300ZX",
    "310",
    "311",
    "350Z",
    "370Z",
    "410",
    "411",
    "510",
    "610",
    "710",
    "810",
    "Almera",
    "Altima",
    "Ariya",
    "Armada",
    "Axxess",
    "B210",
    "Cube",
    "F10",
    "Frontier",
    "GTR",
    "Juke",
    "Kicks",
    "Leaf",
    "Lucino",
    "Maxima (1981 Down)",
    "Maxima (1982 Up)",
    "Micra",
    "Murano",
    "NV 1500",
    "NV 200",
    "NV 2500",
    "NV 3500",
    "NX",
    "Pathfinder",
    "Patrol",
    "Platina",
    "Pulsar",
    "Qashqai",
    "Quest",
    "Rogue",
    "Rogue Sport",
    "Sentra",
    "Stanza (Excl Van)",
    "Stanza Van",
    "Tida",
    "Truck",
    "Truck-Titan",
    "Truck-Titan XD",
    "Tsubame",
    "UD Series",
    "Van GC22",
    "Versa",
    "X Trail",
    "Xterra",
    "Z"
  ],
  "Oldsmobile": [
    "88 (1979 Down)",
    "88 (1980 Up)",
    "98 (1979 Down)",
    "98 (1980 Up)",
    "Achieva",
    "Alero",
    "Aurora",
    "Bravada",
    "Calais (1984 Down)",
    "Calais (1985 Up)",
    "Ciera",
    "Custom Cruiser (1979 Down)",
    "Custom Cruiser (1980 Up)",
    "Cutlass (1972 Down)",
    "Cutlass (1973 Up)",
    "F85",
    "Firenza",
    "Intrigue",
    "Omega",
    "Other",
    "Silhouette",
    "Starfire",
    "Supreme (1972 Down)",
    "Supreme (1973-1987)",
    "Supreme-Calais (1988 Up)",
    "Supreme-Cutlass (1988 Up)",
    "Toronado"
  ],
  "Opel": [
    "Other"
  ],
  "Oshkosh": [
    "Other"
  ],
  "Pace": [
    "Arrow"
  ],
  "Packard": [
    "Other"
  ],
  "Pantera": [
    "Other"
  ],
  "Peterbilt": [
    "Other"
  ],
  "Peugeot": [
    "304",
    "403",
    "404",
    "405",
    "504",
    "505",
    "604"
  ],
  "Plymouth": [
    "Acclaim",
    "Arrow-Car",
    "Arrow-Truck (See also Dodge D50)",
    "Barracuda",
    "Breeze",
    "Caravelle",
    "Champ",
    "Cricket",
    "Duster (1970-1976)",
    "Duster (1979-1980)",
    "Duster (1985-1987)",
    "Duster (1992-1994)",
    "Grand Fury (1979 Down)",
    "Grand Fury (1980 Up)",
    "Horizon",
    "Laser",
    "Neon",
    "Other",
    "Prowler",
    "Reliant",
    "Sapporo",
    "Scamp (1983 only)",
    "Scamp (except 1983)",
    "Sundance",
    "Trailduster",
    "Valiant",
    "Van 100",
    "Van 150",
    "Van 200",
    "Van 250",
    "Van 300",
    "Van 350",
    "Volare",
    "Voyager"
  ],
  "Polestar": [
    "1",
    "2",
    "3",
    "4"
  ],
  "Pontiac": [
    "1000",
    "2000-P/J/Sunbird",
    "6000",
    "Acadian",
    "Astre",
    "Aztek",
    "Bonneville (1979 Down)",
    "Bonneville (1980 Up)",
    "Catalina (1979 Down)",
    "Catalina (1980 Up)",
    "Fiero",
    "Firebird",
    "Firefly",
    "G3",
    "G4",
    "G5",
    "G6",
    "G8",
    "Grand AM",
    "Grand Prix",
    "GTO (New Style)",
    "GTO (Old Style)",
    "Lemans",
    "Matiz",
    "Montana",
    "Other",
    "Parisienne (1979 Down)",
    "Parisienne (1980 Up)",
    "Phoenix",
    "Pursuit",
    "Solstice",
    "Sunbird",
    "Sunburst",
    "Sunfire",
    "Sunrunner",
    "Tempest",
    "Torrent",
    "Trans Sport",
    "Van-Montana",
    "Ventura",
    "Vibe",
    "Wave"
  ],
  "Porsche": [
    "356",
    "911/930",
    "912/e",
    "914",
    "918",
    "924",
    "928",
    "944",
    "968",
    "Boxster",
    "Carrera-GT",
    "Cayenne",
    "Cayman S",
    "Macan",
    "Macan EV",
    "Panamera",
    "Taycan"
  ],
  "Ram": [
    "Promaster 1500",
    "Promaster 2500",
    "Promaster 3500",
    "Promaster City",
    "Promaster EV",
    "Truck 1500 Series",
    "Truck 2500 Series",
    "Truck 3500 Series",
    "Truck 4500 Series",
    "Truck 5500 Series"
  ],
  "Renault": [
    "18I",
    "Alliance",
    "Clio",
    "Dauphine",
    "Encore",
    "Fuego",
    "Gordini",
    "Lecar/R5",
    "Medallion",
    "Megane",
    "Other",
    "R10",
    "R12",
    "R15",
    "R16",
    "R17",
    "R30",
    "R8"
  ],
  "REO": [
    "Other"
  ],
  "Rivian": [
    "R1S",
    "R1T"
  ],
  "RollsRoyce": [
    "Other"
  ],
  "Rover": [
    "100",
    "2000",
    "3 Litre",
    "3500",
    "3500S"
  ],
  "Saab": [
    "9-3 (1999 Up)",
    "9-5 (1999 Up)",
    "900 (incl Turbo)",
    "9000 (incl Turbo)",
    "92x",
    "93 (1960 Down)",
    "94x",
    "95 (1972 Down)",
    "96",
    "97x",
    "99",
    "Monte Carlo",
    "Sonett",
    "Sonett III"
  ],
  "Saturn": [
    "Astra",
    "Aura",
    "EV1",
    "Ion",
    "L Series",
    "Outlook",
    "Relay",
    "S Series",
    "Sky",
    "Vue"
  ],
  "Scion": [
    "FRS",
    "iA",
    "iM",
    "iQ",
    "tC",
    "xA",
    "xB",
    "xD"
  ],
  "Seat": [
    "Cordova",
    "Ibiza",
    "Leon",
    "Toledo"
  ],
  "Simca": [
    "Other"
  ],
  "Smart": [
    "Fortwo"
  ],
  "SterlingRover": [
    "Other"
  ],
  "Studebaker": [
    "Other"
  ],
  "Subaru": [
    "Ascent",
    "Baja",
    "Brat",
    "BRZ",
    "Chaser",
    "Crosstrek",
    "Forester",
    "Impreza",
    "Justy",
    "Legacy",
    "Loyale",
    "Other",
    "Outback (Impreza)",
    "Outback (Legacy)",
    "Sambar",
    "Solterra",
    "Streega",
    "SVX",
    "Tribeca",
    "WRX (2014 Down)",
    "WRX (2015 Up)",
    "XT",
    "XV Crosstrek"
  ],
  "Sunbeam": [
    "Other"
  ],
  "Suzuki": [
    "Aerio",
    "Carry",
    "Equator",
    "Esteem",
    "Forenza",
    "Forsa",
    "Kizashi",
    "Reno",
    "Samurai",
    "Sidekick",
    "SJ410",
    "Swift",
    "SX4",
    "Verona",
    "Vitara",
    "X90",
    "XL7"
  ],
  "Tesla": [
    "Cybertruck",
    "Model 3",
    "Model S",
    "Model X",
    "Model Y",
    "Roadster"
  ],
  "Thomas": [
    "Truck"
  ],
  "Toyota": [
    "4Runner",
    "86",
    "Aristo",
    "Avalon",
    "BZ4X",
    "Camry",
    "Carina",
    "Celica",
    "CHR",
    "Corolla",
    "Corolla Cross",
    "Corolla FX/FX16",
    "Corolla iM",
    "Corona MKII",
    "Corona not MKII",
    "Cressida",
    "Crown",
    "Crown Signia",
    "Echo",
    "FJ Cruiser",
    "FX/FX16",
    "GR Corolla",
    "GR Supra",
    "GR86",
    "Grand Highlander",
    "HiAce",
    "Highlander",
    "Land Cruiser",
    "Matrix",
    "Mirai",
    "MR2",
    "Paseo",
    "Previa",
    "Prius",
    "RAV4",
    "Sequoia",
    "Sienna",
    "Solara",
    "Starlet",
    "Stout",
    "Supra",
    "T100",
    "Tacoma",
    "Tercel",
    "Truck (except T100 & Tundra)",
    "Tundra",
    "Van (See also Previa)",
    "Venza",
    "Yaris",
    "Yaris iA"
  ],
  "Triumph": [
    "GT6",
    "Spitfire",
    "Stag",
    "TR2",
    "TR250",
    "TR3",
    "TR4",
    "TR4A",
    "TR6",
    "TR7",
    "TR8"
  ],
  "Utilimaster": [
    "Step Van"
  ],
  "VinFast": [
    "VF7",
    "VF8",
    "VF9"
  ],
  "Volkswagen": [
    "412/411",
    "Arteon",
    "Atlas",
    "Atlas Cross Sport",
    "Beetle/Bug",
    "Cabrio",
    "Cabriolet",
    "CC",
    "Corrado",
    "Dasher",
    "Derby",
    "Eos",
    "Fox",
    "Golf",
    "Golf GTI",
    "ID.4",
    "ID.Buzz",
    "Jetta",
    "Jetta GLI",
    "Karmann Ghia",
    "Other",
    "Passat",
    "Phaeton",
    "Pointer",
    "Pointer Truck",
    "Quantum",
    "Rabbit",
    "Routan",
    "Scirocco",
    "Sedan",
    "Sharan",
    "Taos",
    "Thing",
    "Tiguan",
    "Touareg",
    "Type 3",
    "Van-EuroVan",
    "Van-Transporter",
    "Van-Vanagon"
  ],
  "Volvo": [
    "120 Series",
    "140 Series",
    "160 Series",
    "1800",
    "240",
    "260",
    "30 Series",
    "40 Series",
    "444/445",
    "50 Series",
    "544",
    "60 Series",
    "70 Series",
    "740",
    "760",
    "780",
    "80 Series",
    "850",
    "90 Series",
    "940",
    "960",
    "C40",
    "EC40",
    "EX30",
    "EX40",
    "EX90",
    "F7",
    "FE6",
    "S60 (2013 Down)",
    "S60 (2014 Up)",
    "S90",
    "Truck",
    "V60",
    "V70",
    "V90",
    "XC40",
    "XC60 (2013 Down)",
    "XC60 (2014 Up)",
    "XC70",
    "XC90"
  ],
  "VPG": [
    "MV1"
  ],
  "Western": [
    "Star"
  ],
  "White": [
    "Other"
  ],
  "Willys": [
    "Other"
  ],
  "Winnebago": [
    "Other"
  ],
  "Yugo": [
    "Other"
  ]
} as const;

export const DOCUMENT_PART_OPTIONS = [
  "A Pillar",
  "A Pillar Trim",
  "A/C Bracket",
  "A/C Compressor",
  "A/C Compressor Clutch Only",
  "A/C Condenser",
  "A/C Condenser Fan",
  "A/C Control Computer",
  "A/C Evaporator",
  "A/C Evaporator Housing only",
  "A/C Heater Control (see also Radio or TV Screen)",
  "A/C Hose",
  "A/C Wiring Harness",
  "Accelerator Cable",
  "Accelerator Pedal",
  "Adaptive Cruise Projector",
  "Air Bag",
  "Air Bag Clockspring",
  "Air Bag Ctrl Module",
  "Air Box/Air Cleaner",
  "Air Cond./Heater Vents",
  "Air Flow Meter",
  "Air Pump",
  "Air Ride Compressor",
  "Air Shutter",
  "Air Tube/Resonator",
  "Alternator",
  "Alternator Bracket",
  "Amplifier/Radio",
  "Antenna",
  "Anti-Lock Brake Computer",
  "Anti-Lock Brake Pump",
  "Armrest",
  "Ash Tray/Lighter",
  "Audiovisual (A/V) (see also TV Screen)",
  "Auto. Trans. Cooler",
  "Automatic Headlight Dimmer",
  "Axle Actuator (4WD)",
  "Axle Assy Fr (4WD w. Housing)",
  "Axle Assy Rear (w. Housing)",
  "Axle Beam Front (2WD, incl I Beam Susp)",
  "Axle Beam Rear (FWD)",
  "Axle Flange",
  "Axle Housing Only",
  "Axle Shaft",
  "B Pillar Trim",
  "Back Door Glass",
  "Back Door Handle, Inside",
  "Back Door Handle, Outside",
  "Back Door Hinge",
  "Back Door Moulding",
  "Back Door Shell",
  "Back Door Trim Panel",
  "Back Door(above bmpr-see also Door Shell, Back)",
  "Back Glass",
  "Back Glass Regulator",
  "Back Glass Shock",
  "Backing Plate, Front",
  "Backing Plate, Rear",
  "Backup Camera",
  "Backup Light",
  "Battery",
  "Battery Cable",
  "Battery Cooling Fan",
  "Battery Terminal",
  "Battery Tray",
  "Bed Floor (Pickup)",
  "Bed Front Panel (Pickup)",
  "Bed Liner",
  "Bed Side, Pickup",
  "Bed, Pickup",
  "Bell Housing",
  "Belt Tensioner",
  "Blind Spot Camera",
  "Blower Motor",
  "Blower Motor Resistor",
  "Body Wiring Harness",
  "Brake Booster",
  "Brake Proportioning Valve",
  "Brake Rotor/Drum, Front",
  "Brake Rotor/Drum, Rear",
  "Brake Shoes/Pads",
  "Brake/Clutch Pedal",
  "Brush Guard",
  "Bug Screen",
  "Bumper Assy (Front) includes cover",
  "Bumper Assy (Rear) includes cover",
  "Bumper Bracket (Misc)",
  "Bumper Cover (Front)",
  "Bumper Cover (Rear)",
  "Bumper End Cap",
  "Bumper Energy Absorber (Front)",
  "Bumper Energy Absorber (Rear)",
  "Bumper Face Bar (Front)",
  "Bumper Face Bar (Rear)",
  "Bumper Filler Panel",
  "Bumper Guard (Front)",
  "Bumper Guard (Rear)",
  "Bumper Impact Strip",
  "Bumper Reinforcement (Front)",
  "Bumper Reinforcement (Rear)",
  "Bumper Shock",
  "Bumper Step Pad",
  "C Pillar Trim",
  "Cab",
  "Cab Back Panel",
  "Cab Clip, no cowl",
  "Cab Corner",
  "Cab Marker/Clearance Lamp",
  "Cabin Air Filter",
  "Cabin Fuse Box",
  "Caliper",
  "Camera Projector",
  "Camshaft",
  "Camshaft Housing",
  "Carburetor (see also Throttle Body)",
  "Cargo Cover/Shade",
  "Cargo Lamp",
  "Carpet",
  "Carrier (see also Differential)",
  "Carrier Case",
  "CD Player/Radio",
  "Center Cap (Wheel)",
  "Center Pillar",
  "Charging Port Door Assembly",
  "Chassis Control Computer (not Engine)",
  "Clock",
  "Clockspring (Air Bag)",
  "Clutch Cable",
  "Clutch Disc",
  "Clutch Fork",
  "Clutch Master Cylinder",
  "Coil/Air Spring",
  "Coil/Igniter",
  "Column Switch",
  "Computer Box Engine",
  "Computer Box Not Engine",
  "Condenser",
  "Condenser/Radiator mtd. Cooling Fan",
  "Connecting Rod, Engine",
  "Console Lid",
  "Console, Front",
  "Console, Rear",
  "Control Arm, Front Lower",
  "Control Arm, Front Upper",
  "Control Arm, Rear Lower",
  "Control Arm, Rear Upper",
  "Convertible Top",
  "Convertible Top Boot",
  "Convertible Top Lift",
  "Convertible Top Motor",
  "Convertible Windscreen",
  "Coolant Pump",
  "Cooling Fan (Rad and Con mtd.)",
  "Core (Radiator) Support",
  "Cowl",
  "Cowl Vent/Screen Panel",
  "Crank Pulley (Harmonic Balancer)",
  "Crankshaft",
  "Cruise Control Computer",
  "Cruise Control Servo/Regulator",
  "Cruise Speed Controler",
  "Cylinder Head (Engine)",
  "D Pillar",
  "Dash Bezel (see also Instrument or Radio Bezel)",
  "Dash Pad",
  "Dash Panel",
  "Dash Wiring Harness",
  "Dash/Interior Switch",
  "Deck Lid Assembly",
  "Deck Lid Latch",
  "Deck Lid Lock",
  "Deck Lid/Trunk Lid Shell",
  "Diesel Particulate Filter",
  "Differential Assembly (see also Carrier)",
  "Differential Case Only",
  "Differential Flange Only",
  "Distributor",
  "Distributor Cap",
  "Door Back(above bmpr-see also Door Shell, Back)",
  "Door Front (see also Door Shell, Front)",
  "Door Handle, Inside",
  "Door Handle, Outside",
  "Door Lock Assembly",
  "Door Lock Striker",
  "Door Mirror Cover",
  "Door Outer Repair Panel, Back",
  "Door Outer Repair Panel, Front",
  "Door Outer Repair Panel, Rear",
  "Door Rear (side-see also Door Shell, Rear)",
  "Door Shell, Back (see also Door Back)",
  "Door Shell, Front (see also Door Front)",
  "Door Shell, Rear (see also Door Rear)",
  "Door Window Crank Handle",
  "Drag Link",
  "Drive Shaft, Front",
  "Drive Shaft, Rear",
  "Drive-By-Wire",
  "Driving Lamp Bezel",
  "EGR Valve",
  "Electric Door Motor (not Window)",
  "Electric Window Motor",
  "Electrical Part Misc",
  "Electronic Transmission Shifter",
  "Emblem",
  "Emergency Brake",
  "Engine",
  "Engine Block",
  "Engine Computer",
  "Engine Core",
  "Engine Cover",
  "Engine Cradle",
  "Engine Cylinder Head",
  "Engine Fuse Box",
  "Engine Mounts",
  "Engine Oil Pan",
  "Engine Wiring Harness",
  "Exhaust Assembly",
  "Exhaust Cross Pipe",
  "Exhaust Fluid Pump",
  "Exhaust Fluid Tank",
  "Exhaust Heat Shield",
  "Exhaust Lead Pipe",
  "Exhaust Manifold",
  "Exhaust Muffler",
  "Exhaust Pipe",
  "Exhaust Resonator",
  "Exhaust Tail Pipe",
  "Fan Blade",
  "Fan Clutch",
  "Fender",
  "Fender Extension",
  "Fender Flare",
  "Fender Inner Panel",
  "Fender Moulding",
  "Fender Skirt",
  "Fender/Wheelhouse Inner Liner",
  "Flex Plate",
  "Floor Mats",
  "Floor Pan",
  "Floor Shift Assembly",
  "Flywheel",
  "Fog Lamp",
  "Fog Lamp Bezel",
  "Fog Lamp Bracket",
  "Fog Lamp Rear",
  "Fog Lamp Switch",
  "Frame",
  "Frame Front Section Only",
  "Frame Horn",
  "Frame Upper & Lower Rails",
  "Front Axle Assembly (4WD w Housing)",
  "Front Axle Beam (2WD, incl I Beam Susp)",
  "Front Axle Shaft",
  "Front Bumper Assembly (includes cover)",
  "Front Bumper Cover",
  "Front Bumper Face Bar",
  "Front Bumper Guard",
  "Front Bumper Reinforcement",
  "Front Console",
  "Front Door (see also Door Shell, Front)",
  "Front Door Glass",
  "Front Door Handle, Inside",
  "Front Door Handle, Outside",
  "Front Door Hinge",
  "Front Door Mirror",
  "Front Door Mirror Glass",
  "Front Door Moulding",
  "Front Door Regulator",
  "Front Door Shell",
  "Front Door Switch",
  "Front Door Trim Panel",
  "Front Door Vent Glass",
  "Front Door Vent Glass Regulator",
  "Front Door Window Motor",
  "Front Drive Shaft",
  "Front End Assembly (Nose)",
  "Front Inner Structure",
  "Front Seat Belt Assembly",
  "Front Valance",
  "Front Window Regulator",
  "Fuel Cap",
  "Fuel Cell",
  "Fuel Cooler",
  "Fuel Distributor (& Misc. Injection)",
  "Fuel Filler Door",
  "Fuel Filler Neck",
  "Fuel Gauge",
  "Fuel Injector (& Misc. Injection)",
  "Fuel Injector Pump",
  "Fuel Injector Rail",
  "Fuel Line",
  "Fuel Pump",
  "Fuel Tank",
  "Fuel Tank Sending Unit",
  "Fuse Box (Cabin)",
  "Fuse Box (Engine)",
  "Fuse Box Cooling Fan",
  "Gas Cap",
  "Gas Pedal",
  "Gas Tank",
  "Gate Interior Trim Panel",
  "Gate Window Regulator",
  "Gate/Lid",
  "Gauge (Misc)",
  "Gear Shift Indicator",
  "Generator",
  "Glass, Back",
  "Glass, Front Door",
  "Glass, Front Vent",
  "Glass, Quarter Window",
  "Glass, Rear Door",
  "Glass, Rear Vent",
  "Glass, Special (see also Sunroof/TTop)",
  "Glass, Windshield",
  "Glove Box",
  "Glove Box Door",
  "Glove Box Lock",
  "GPS Screen (see also Radio or Heater/AC Control)",
  "Grille",
  "Grille Moulding",
  "Grille Surround",
  "Harmonic Balancer (Crank Pulley)",
  "Hatch/Trunk Lid",
  "Head (Cylinder)",
  "Header Panel",
  "Headlight Assembly",
  "Headlight Ballast",
  "Headlight Bracket",
  "Headlight Bucket",
  "Headlight Bulb",
  "Headlight Cover (Plastic)",
  "Headlight Door",
  "Headlight Housing",
  "Headlight Igniter",
  "Headlight Lens",
  "Headlight Motor",
  "Headlight Switch (Column Mounted)",
  "Headlight Switch (Dash Mounted)",
  "Headlight Switch (see also Column Switch)",
  "Headlight Washer Motor Only",
  "Headlight Wiper Motor Only",
  "Headliner",
  "Headrest",
  "Heads Up Display",
  "Heat Pump Reversing Valve",
  "Heater Assy",
  "Heater Core",
  "Heater Motor",
  "Heater/AC Control (see also Radio or TV Screen)",
  "Hood",
  "Hood Deflector",
  "Hood Hinge",
  "Hood Insulation Pad",
  "Hood Latch",
  "Hood Ornament",
  "Hood Prop",
  "Hood Release Cable",
  "Hood Release Handle",
  "Hood Scoop",
  "Hood Shock",
  "Horn",
  "Hub",
  "Hub Cap/Wheel Cover (display w image)",
  "Hub Cap/Wheel Cover (display w/o image)",
  "Hub, Lockout (4WD)",
  "HVAC Actuator",
  "Hybrid Converter/Inverter",
  "Idler Arm",
  "Ignition Module (see also Ignitor/Coil)",
  "Ignition Switch",
  "Ignitor/Coil",
  "Info Screen (see also Radio or Heater/AC Control)",
  "Information Label",
  "Inside Door Handle",
  "Instrument Cluster (see also Speedo)",
  "Instrument Cluster Bezel",
  "Instrument Face Plate",
  "Intake Manifold",
  "Intercooler",
  "Intercooler Pipe",
  "Interior Complete",
  "Interior Light",
  "Interior Trim Panel (Gate/Lid)",
  "Interior Trim Panel (Quarter)",
  "Interior Trim Panel, Door (Back)",
  "Interior Trim Panel, Door (Front)",
  "Interior Trim Panel, Door (Rear)",
  "Inverter Cooler",
  "Jack Assembly",
  "Key Remote/Fob",
  "Keys/Latches and Locks",
  "Kick Panel",
  "Knee Assembly (see also Strut Assy)",
  "Lamp Wiring Harness",
  "Latch, Back Door",
  "Latch, Front Door",
  "Latch, Rear Door",
  "Latches (Misc)",
  "Leaf Spring, Front",
  "Leaf Spring, Rear",
  "License Lamp",
  "License Plate Bracket",
  "Lid Interior Trim Panel",
  "Lid/Gate",
  "Liftgate Assembly",
  "Liftgate Latch",
  "Liftgate Lock",
  "Liftgate Shell",
  "Lock Actuator",
  "Lockout Hub, 4X4",
  "Locks (Misc)",
  "Lug Wrench",
  "Luggage Rack",
  "Marker/Fog Light, Front",
  "Marker/Side Light, Rear",
  "Master Cylinder",
  "Mirror, Door",
  "Mirror, Rear View",
  "Misc. Electrical",
  "Moulding (Back Door)",
  "Moulding (Fender)",
  "Moulding (Front Door)",
  "Moulding (Lid/Hatch/Gate)",
  "Moulding (Quarter Panel/Bed Side)",
  "Moulding (Rear Door)",
  "Moulding (Rocker)",
  "Moulding (Windshield)",
  "Mouldings (Misc)",
  "Mud Flap",
  "Neutral Safety Switch",
  "Night Vision Camera",
  "Nose (Front End Assembly)",
  "Oil Cooler (Engine)",
  "Oil Cooler (Transmission)",
  "Oil Filter Adapter",
  "Oil Filter Housing",
  "Oil Pan, Engine",
  "Oil Pan, Transmission",
  "Oil Pump, Engine",
  "Outside Door Handle",
  "Overdrive Unit (see also Transmission)",
  "Owners Manual",
  "Paddle Shifter",
  "Parcel Shelf",
  "Park Lamp Rear (Side)",
  "Park/Fog Lamp Front",
  "Parking Assist Camera",
  "Pickup Bed",
  "Pickup Bed Floor",
  "Pickup Bed Front Panel",
  "Pickup Bed Side",
  "Pickup Cap/Camper Shell",
  "Piston",
  "Pitman Arm",
  "Power Brake Booster",
  "Power Inverter (Hybrid)",
  "Power Steering Assy",
  "Power Steering Control Valve",
  "Power Steering Cooler",
  "Power Steering Motor",
  "Power Steering Pressure Cyl",
  "Power Steering Pressure Hose",
  "Power Steering Pump",
  "Power Steering Rack/Box/Gear",
  "Power Steering Reservoir",
  "Pressure Plate",
  "Push Rod (Engine)",
  "Quarter Interior Trim Panel",
  "Quarter Moulding",
  "Quarter Panel",
  "Quarter Panel Extension",
  "Quarter Repair Panel",
  "Quarter Window",
  "Quarter Window Latch",
  "Quarter Window Motor",
  "Quarter Window Regulator",
  "Rack & Pinion (Steering)",
  "Radar Unit",
  "Radiator",
  "Radiator Air Shutter",
  "Radiator Core Support",
  "Radiator Cover Baffle",
  "Radiator Fan Shroud",
  "Radiator Overflow Bottle",
  "Radiator/Condenser mtd. Cooling Fan",
  "Radio Bezel Trim",
  "Radio Face Plate",
  "Radio/CD (see also A/C Control or TV Screen)",
  "Radius Arm, Front",
  "Rag Joint (see also Steering Coupler)",
  "Rear Axle Assy (RWD)",
  "Rear Axle Beam (FWD)",
  "Rear Body Panel",
  "Rear Bumper Assembly (includes cover)",
  "Rear Bumper Cover",
  "Rear Bumper Face Bar",
  "Rear Bumper Guard",
  "Rear Bumper Reinforcement/Misc",
  "Rear Clip",
  "Rear Console",
  "Rear Crossmember",
  "Rear Door (side-see also Door Shell, Rear)",
  "Rear Door Handle, Inside",
  "Rear Door Handle, Outside",
  "Rear Door Hinge",
  "Rear Door Moulding",
  "Rear Door Regulator",
  "Rear Door Shell",
  "Rear Door Switch",
  "Rear Door Trim Panel",
  "Rear Door Vent Glass",
  "Rear Door Vent Glass regulator",
  "Rear Door Window",
  "Rear Door Window Motor",
  "Rear Door Window Regulator",
  "Rear Drive Shaft",
  "Rear Finish Panel",
  "Rear Gate Window Motor",
  "Rear Gate/Lid",
  "Rear Knuckle/Stub Axle",
  "Rear Lower Valance",
  "Rear Seat Belt Assembly",
  "Rear Suspension (see also Control Arms)",
  "Rear Suspension Locating Arm",
  "Rear Suspension Trailing Arm",
  "Rear Window Defogger",
  "Rear Window Washer Motor",
  "Receiver Dryer",
  "Relay (Misc)",
  "Ring and Pinion Only",
  "Rocker Arm",
  "Rocker Moulding",
  "Rocker Panel (see also Center Pillar)",
  "Roll Bar",
  "Roll Bar Padding",
  "Roof",
  "Roof Glass Frame/Track",
  "Roof Panel (see also Sunroof)",
  "Roof Rack",
  "Running Board Motor",
  "Running Boards",
  "Satellite Receiver",
  "Seat Belt Motor",
  "Seat Belt Pretensioner",
  "Seat Belt Track (Electric)",
  "Seat Belt, Front",
  "Seat Belt, Rear",
  "Seat Motor",
  "Seat Switch",
  "Seat Track, Front Only",
  "Seat, Back (3rd Row)",
  "Seat, Back (4th Row)",
  "Seat, Back (5th Row)",
  "Seat, Front",
  "Seat, Rear (2nd Row)",
  "Sensor (Body, Misc)",
  "Sensor (Chassis, Misc)",
  "Sensor (Drivetrain, Misc)",
  "Shifter Assembly (Floor)",
  "Shifter Cable",
  "Shifter Linkage",
  "Shock Absorber",
  "Shock Mount",
  "Short Block",
  "Sill Plate",
  "Skid Plate",
  "Slave Cylinder",
  "Smog Pump",
  "Spare Tire Carrier",
  "Spare Tire Cover",
  "Spare Tire Hoist",
  "Spark Plug Wire",
  "Speaker",
  "Special Glass",
  "Speedometer (see also Instr. Cluster)",
  "Speedometer Cable",
  "Spindle",
  "Spoiler, Front",
  "Spoiler, Rear",
  "Spring Hanger",
  "Stabilizer Bar Only",
  "Starter",
  "Steering Column",
  "Steering Column Shaft",
  "Steering Coupler",
  "Steering Knuckle (see also Knee & Strut)",
  "Steering Pump",
  "Steering Rack/Box/Gear",
  "Steering Wheel",
  "Strut (see also Knee Assy)",
  "Strut Tower Brace",
  "Sub Frame, Front",
  "Sub Frame, Rear",
  "Sun Roof / T-Top",
  "Sun Roof Motor",
  "Sunvisor",
  "Supercharger/Turbocharger",
  "Tachometer",
  "Tail Light",
  "Tail Light Circuit Board",
  "Tail Light Lens",
  "Tailgate Cable",
  "Tailgate Hinge",
  "Tailgate Latch",
  "Tailgate Lift Motor",
  "Tailgate Lock",
  "Tailgate Shell",
  "Tailgate Window Regulator",
  "Tailgate/Trunk Lid",
  "Thermostat Housing",
  "Third Brake Light",
  "Throttle Body/Throttle Valve Housing",
  "Throwout Bearing",
  "Tie Rod",
  "Timing Belt/Chain",
  "Timing Cover",
  "Timing Gears",
  "Tire",
  "Tonneau Cover",
  "Torque Convertor",
  "Torsion Bar",
  "Tow Hook",
  "Track/Watts Linkage",
  "Trailer Brake Controller",
  "Trailer Hitch",
  "Trans OD Unit (see also Transmission)",
  "Transaxle Housing Only",
  "Transfer Case",
  "Transfer Case Adapter",
  "Transfer Case Core",
  "Transfer Case Electric Motor",
  "Transfer Case Switch",
  "Transmission",
  "Transmission Bellhousing Only",
  "Transmission Clutch Actuator",
  "Transmission Computer",
  "Transmission Cooling Line",
  "Transmission Core",
  "Transmission Crossmember",
  "Transmission Front Pump",
  "Transmission Mount",
  "Transmission Oil Cooler",
  "Transmission Pan",
  "Transmission Torque Converter",
  "Transmission Valve Body",
  "Transmission Wiring Harness",
  "Trim Ring",
  "Trunk Lid Pull Down Motor",
  "Trunk Lid/Hatch",
  "Trunk Lid/Hatch Hinge",
  "Trunk Lid/Hatch Shock",
  "Trunk Lid/Tailgate Moulding",
  "TTop/Sunroof",
  "Turbo/Supercharger Core",
  "Turbocharger/Supercharger",
  "Turn Signal/Fog Lamp",
  "TV Screen (see also Radio or Heater/AC Control)",
  "Uniside",
  "Utility Bed",
  "Utility Box",
  "Vacuum Pump",
  "Vacuum Storage Tank",
  "Valance, Front",
  "Valance, Rear",
  "Valve Cover",
  "Vapor Canister",
  "Voltage Regulator",
  "Washer Nozzle",
  "Water Pump",
  "Water Separator",
  "Weather Stripping",
  "Wheel (display w image)",
  "Wheel (display w/o image)",
  "Wheel Bearing",
  "Wheel Cover/Hubcap (display w image)",
  "Wheel Cover/Hubcap (display w/o image)",
  "Wheel Lug Nut",
  "Wheel Opening Moulding",
  "Wheelchair Lift",
  "Wheelchair Ramp",
  "Wheelhouse (Rear)",
  "Winch",
  "Window Motor",
  "Window Regulator (Front)",
  "Window Regulator (Rear)",
  "Window Shade",
  "Window Switch (Front Door)",
  "Window Switch (Rear Door)",
  "Window Washer Motor, Rear",
  "Windshield",
  "Windshield Frame",
  "Windshield Hinge",
  "Windshield Washer Motor (Front)",
  "Windshield Washer Reservoir",
  "Wiper Arm",
  "Wiper Linkage",
  "Wiper Motor, Front (Windshield)",
  "Wiper Motor, Rear",
  "Wiring Harness (Air Conditioning)",
  "Wiring Harness (Body)",
  "Wiring Harness (Dash)",
  "Wiring Harness (Engine)",
  "Wiring Harness (Lamp)",
  "Wiring Harness (Misc)",
  "Wiring Harness (Transmission)",
  "Yoke/U-Joint"
] as const;
