ALTER TYPE "ReplacementStatus" ADD VALUE IF NOT EXISTS 'AGREED';
ALTER TYPE "ReplacementStatus" ADD VALUE IF NOT EXISTS 'DISAGREED';
ALTER TYPE "ReplacementStatus" ADD VALUE IF NOT EXISTS 'YARD_REFUNDING';
ALTER TYPE "ReplacementStatus" ADD VALUE IF NOT EXISTS 'YARD_DOESNT_HAVE_REPLACEMENT';
